CREATE TABLE purchase_order_tm (
    "eventID" VARCHAR(255) PRIMARY KEY,
    "caseID" VARCHAR(255),
    "purchasing_document" VARCHAR(255),
    "item" VARCHAR(255),
    "activity" VARCHAR(255),
    "purch_doc_category_name" VARCHAR(255),
    "item_category" VARCHAR(255),
    "goods_receipt" VARCHAR(255),
    "gr_based_iv" VARCHAR(255),
    "document_type" VARCHAR(255),
    "item_type" VARCHAR(255),
    "spend_classification_text" VARCHAR(255),
    "spend_area_text" VARCHAR(255), 
    "subspend_area_text" VARCHAR(255),
    "company" VARCHAR(255),
    "source" VARCHAR(255),
    "vendor" VARCHAR(255),
    "vendor_name" VARCHAR(255),
    "timestamp" VARCHAR(255),
    "event_user" VARCHAR(255),
    "event_resource" VARCHAR(255),
    "event_cumulative_net_worth" DECIMAL(18,2)
);

INSERT INTO purchase_order_tm (
    "eventID",
    "caseID",
    "purchasing_document",
    "item",
    "activity",
    "purch_doc_category_name",
    "item_category",
    "goods_receipt",
    "gr_based_iv",
    "document_type",
    "item_type",
    "spend_classification_text",
    "spend_area_text", 
    "subspend_area_text",
    "company",
    "source",
    "vendor",
    "vendor_name",
    "timestamp",
    "event_user",
    "event_resource",
    "event_cumulative_net_worth"
)
SELECT 
    "eventID",
    "case concept:name",
    "case Purchasing Document",
    "case Item",
    "event concept:name",
    "case Purch. Doc. Category name",
    "case Item Category",
    "case Goods Receipt",
    "case GR-Based Inv. Verif.",
    "case Document Type",
    "case Item Type",
    "case Spend classification text",
    "case Spend area text", 
    "case Sub spend area text",
    "case Company",
    "case Source",
    "case Vendor",
    "case Name",
    "event time:timestamp",
    "event User",
    "event org:resource",
    "event Cumulative net worth (EUR)"
FROM "DBADMIN"."purchase_order_raw_tm";